//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labyrinthe.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class QuantiteLoot : global::System.Configuration.ApplicationSettingsBase {
        
        private static QuantiteLoot defaultInstance = ((QuantiteLoot)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new QuantiteLoot())));
        
        public static QuantiteLoot Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int nbCartes {
            get {
                return ((int)(this["nbCartes"]));
            }
            set {
                this["nbCartes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int nbClés {
            get {
                return ((int)(this["nbClés"]));
            }
            set {
                this["nbClés"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int nbPotionVision {
            get {
                return ((int)(this["nbPotionVision"]));
            }
            set {
                this["nbPotionVision"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int nbPotionForce {
            get {
                return ((int)(this["nbPotionForce"]));
            }
            set {
                this["nbPotionForce"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int nbPotionVitesse {
            get {
                return ((int)(this["nbPotionVitesse"]));
            }
            set {
                this["nbPotionVitesse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int nbSortVision {
            get {
                return ((int)(this["nbSortVision"]));
            }
            set {
                this["nbSortVision"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int nbSortForce {
            get {
                return ((int)(this["nbSortForce"]));
            }
            set {
                this["nbSortForce"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int nbSortVitesse {
            get {
                return ((int)(this["nbSortVitesse"]));
            }
            set {
                this["nbSortVitesse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int nbSortTeleportation {
            get {
                return ((int)(this["nbSortTeleportation"]));
            }
            set {
                this["nbSortTeleportation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int nbCarteForce {
            get {
                return ((int)(this["nbCarteForce"]));
            }
            set {
                this["nbCarteForce"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int nbCarteVitesse {
            get {
                return ((int)(this["nbCarteVitesse"]));
            }
            set {
                this["nbCarteVitesse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int nbCarteTeleportation {
            get {
                return ((int)(this["nbCarteTeleportation"]));
            }
            set {
                this["nbCarteTeleportation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int nbEtre {
            get {
                return ((int)(this["nbEtre"]));
            }
            set {
                this["nbEtre"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int nbPic {
            get {
                return ((int)(this["nbPic"]));
            }
            set {
                this["nbPic"] = value;
            }
        }
    }
}
